apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app-deployment
spec:
  selector:
    matchLabels:
      app: social-media-app
  replicas: 2  # Start with 2 replicas, can be scaled with HPA
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
        - name: social-media-app
          image: malekjellali1/social-media-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "socialMedia"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 3
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-app-svc
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: NodePort  # You can switch to LoadBalancer or ClusterIP for other environments
