apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app-deployment
spec:
  selector:
    matchLabels:
      app: social-media-app
  replicas: 2
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
        - name: social-media-app
          image: malekjellali1/social-media-app:latest # Public image from DockerHub
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: MYSQL_HOST
              value: "mysql"  # The MySQL service name in the same namespace
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "socialMedia"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"  # Make sure this matches the MySQL password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10  # Delay before the first probe attempt
            periodSeconds: 5         # Interval between probes
            timeoutSeconds: 3        # How long to wait for a response
            failureThreshold: 3      # Number of failed probes before marking the pod as unhealthy

---
apiVersion: v1
kind: Service
metadata:
  name: social-media-app-svc
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: NodePort # Use NodePort for local testing in Minikube
