apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app-deployment
spec:
  selector:
    matchLabels:
      app: social-media-app
  replicas: 2
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
        - name: social-media-app
          image: malekjellali1/social-media-app:latest # Public image from DockerHub
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /actuator/health # Adjust this based on your app's health endpoint
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-app-svc
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: NodePort # Use NodePort for local testing in Minikube


