apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app-deployment
spec:
  selector:
    matchLabels:
      app: social-media-app
  replicas: 2
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
        - name: social-media-app
          image: malekjellali1/social-media-app:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
      imagePullSecrets:
        - name: mysecret # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-app-svc
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: LoadBalancer
