version: '3.8'

services:
  springboot-app:
    image: malekjellali1/social-media-app:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer:3306/socialMedia
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysqlcontainer                 # Ensures MySQL starts before the Spring Boot app

  mysqlcontainer:
    image: mysql:8.0                   # MySQL image version
    ports:
      - "3307:3306"                    # Map MySQL's port 3306 to 3307 on the host
    environment:
      MYSQL_ROOT_PASSWORD: admin       # Root password for MySQL
      MYSQL_DATABASE: socialMedia      # Create `socialMedia` database
      MYSQL_USER: admin                # Non-root user with privileges on `socialMedia`
      MYSQL_PASSWORD: admin            # Password for non-root user
    volumes:
      - db-data:/var/lib/mysql          # Persist MySQL data

volumes:
  db-data:                              # Named volume for persisting database data
