apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  root-password: YWRtaW4=  # Base64 encoded "admin"
  username: YWRtaW4=  # Base64 encoded "admin"
  password: YWRtaW4=  # Base64 encoded "admin"
